setup.cfg: Update `description-file` to `description_file`
This was causing an issue with Python 3.12.4 upon install:

```
    File "/tmp/pip-build-env-yomuui17/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 629, in _enforce_underscore
      raise InvalidConfigError(
  setuptools.errors.InvalidConfigError: Invalid dash-separated key 'description-file' in 'metadata' (setup.cfg), please use the underscore name 'description_file' instead.
```